### PR TITLE
Closes #35 moved presentation archive to gt

### LINKED ISSUE #35: Presentation Archive Glowup
We're currently using a markdown table to show the available presentations/resources.
image

We could give the table a glow-up by using gt. This will allow us to control the column widths (the title should be longer than the others), the links to the resources could use cute fontawesome icons, e.g. 
video 
image
slides 
image
manuscript 
image

@manciniedoardo this is your vignette, so i'll leave it up to you how you'd like to update or not!

### PR DESCRIPTION
**Pull request by manciniedoardo**
Closes #35

### CODE REVIEW

**Comment by manciniedoardo** [comment]
@ddsjoberg I think I've successfully moved to using `gt`, only thing I can't figure out is why my columns are not bold and why their width is not being controlled... any ideas?

Also I guess I haven't looked at using icons yet but can do that later.

**Comment by ddsjoberg** [comment]
hey hey @manciniedoardo ! thanks for the PR, the table looks great!

I see that you made the presentation history an data set saved with the package. If we go that route, you'll need to add data documentation to `data.R`. I see you added it below the discovery data frame, but it needs to be preceded by roxygen comments for that data frame to avoid this note i the r cmd check

image

Since there are only 10 rows in the data frame, I don't think we need to make it an interactive table. If you remove the interactivity, the column widths will be as you've specified.

Thanks!

**Comment by ddsjoberg** [comment]
Looks almost perfect! I see the roxygen2 comments for the data set docs, but it looks like you'll need to re-document and push to get the Rd file. There is also a small typo in the data set documentation "fo" instead of "of"

**Review by ddsjoberg — APPROVED** [review]
Looks great!

**Pull request merged**
