### PR TITLE
#43 #44 Added new presenters and added presenter names

### LINKED ISSUE #43: Name(s) of presenter
Could we add a column for the legends who presented?

image

### LINKED ISSUE #44: Update list of conference presentations
See [here](https://github.com/pharmaverse/admiral/discussions/2394)

### PR DESCRIPTION
**Pull request by manciniedoardo**
Closes #43 Closes #44

### CODE REVIEW

**Comment by manciniedoardo** [comment]
@bms63 do you know who presented "An overview of {admiral}" in 2023? That's the only one for whom i could not find a presenter

**Comment by bms63** [comment]
> @bms63 do you know who presented "An overview of {admiral}" in 2023? That's the only one for whom i could not find a presenter

I do not know.  I would ping the slack channel

**Review by ddsjoberg — CHANGES_REQUESTED** [review]
@manciniedoardo ping me when this is ready for review and the CI/CD is passing. Thanks!

**Comment by manciniedoardo** [comment]
@ddsjoberg sorry, i had logged off without checking the outcome of the first round of checks 😆 

I think i fixed most now, the final lintr stuff might need a small update as i think we deactivate those specific checks in the main admiral packages?

**Review by ddsjoberg — APPROVED** [review]
Looks good!

**Pull request merged**
